[package]
name = "llmchain-loaders"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "A Rust framework for large language models, inspired by LangChain"
categories = ["LLM"]
keywords = ["LLM"]

[dependencies]
async-trait = "0.1.68"
anyhow = "1.0.58"
opendal = "0.33.2"
regex = "1.8.1"
tokio = { version = "1.28.0", features = ["full"]}

[dev-dependencies]
goldenfile = "1.4"
